targets:
  $default:
    sources:
      - $package$
      - lib/$lib$
      - protos/**  # Caminho para o arquivo .proto
    builders:
      protoc_builder:
        options:
          protobuf_version: "3.1.0"
          # The version of the Dart protoc_plugin package to use.
          # (Default: "20.0.1", make sure to use quotation marks)
          protoc_plugin_version: "21.1.2"
          out_dir: "lib/src/dart"
          root_dir: "protos/"
          # Include paths given to the Protobuf compiler during compilation.
          # (Default: ["proto/"])
          proto_paths:
            - "protos/"
          use_installed_protoc: true 