name: app_cep
description: testando

# Versão do projeto
version: 1.0.0

# Ambiente do projeto
environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependências do projeto
dependencies:
  flutter:
    sdk: flutter

  # Dependência para compilar protos
  protobuf: ^3.0.0

# Dev Dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.0
  protoc_builder: ^0.4.1

# Configuração de assets (se necessário)
# assets:
#   - assets/meu_arquivo.proto
