name: Build Proto to Dart

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
    paths:
      - 'proto/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Dart SDK
      run: |
        sudo apt-get update
        sudo apt-get install apt-transport-https
        sudo sh -c 'wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
        sudo sh -c 'wget -qO- https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list'
        sudo apt-get update
        sudo apt-get install dart

    - name: Install Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.10.5'  # Substitua pela versão do Flutter que você está usando

    - name: Run protoc_builder
      run: flutter pub run build_runner build --delete-conflicting-outputs

    - name: Commit and push changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add .
        git commit -m "Update Dart files generated from Proto"
        git push
