name: Build Proto to Dart

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      path:
        description: 'Path to trigger workflow'
        required: false
        default: 'proto/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Use installed Dart SDK
    - name: Use installed Dart SDK
      run: export PATH="$PATH":"/path/to/dart-sdk/bin"

    # Instalar o SDK do Flutter (substitua a versão pelo que você precisa)
    - name: Install Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.9'  # Substitua pela versão do Flutter que você está usando

    - name: Flutter pub get
      run: flutter pub get

    - name: Run protoc_builder
      run: flutter pub run build_runner build --delete-conflicting-outputs

    - name: Commit and push changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add .
        git commit -m "Update Dart files generated from Proto"
        git push

