name: Build Proto to Dart

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
    paths:
      - 'proto/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Instalar o SDK do Dart usando a ação de configuração do Dart
    - name: Setup Dart SDK
      uses: dart-lang/setup-dart@v1
      with:
        sdk: '3.2.6'  # Versão específica do SDK do Dart

    # Instalar o SDK do Flutter
    - name: Install Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.10.5'  # Substitua pela versão do Flutter que você está usando

    # Restante do seu fluxo de trabalho
    - name: Flutter pub get
      run: flutter pub get

    - name: Run protoc_builder
      run: flutter pub run build_runner build --delete-conflicting-outputs

    - name: Commit and push changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add .
        git commit -m "Update Dart files generated from Proto"
        git push
